excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://miyagui.github.io
title: Jonathan Montesinos
tagline: Food for thought
description: This is me in my most nerdy self.
paginate: 5